# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: test_app_development
  username: postgres
  password: 123456
  encoding: unicode
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: test_app_tes
  username: postgres
  password: 123456
  encoding: unicode
  host: localhost
  pool: 5
